CREATE TABLE PROJETO (
    ID INT GENERATED ALWAYS AS IDENTITY,
    NOME VARCHAR(255) NOT NULL,
    DATA_CADASTRO TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT PK_PROJETO PRIMARY KEY (ID)
);

CREATE TABLE USUARIO (
    ID INT GENERATED ALWAYS AS IDENTITY,
    NOME VARCHAR(255) NOT NULL,
    SENHA VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    DATA_CADASTRO TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT PK_USUARIO PRIMARY KEY (ID),
    CONSTRAINT UK_USUARIO_EMAIL UNIQUE (EMAIL)
);

CREATE TABLE USUARIO_PROJETO (
    USUARIO_ID INT NOT NULL,
    PROJETO_ID INT NOT NULL,
    CONSTRAINT PK_USUARIO_PROJETO PRIMARY KEY (USUARIO_ID, PROJETO_ID),
    CONSTRAINT FK_USUARIO_PROJETO_USUARIO FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO(ID) ON DELETE CASCADE,
    CONSTRAINT FK_USUARIO_PROJETO_PROJETO FOREIGN KEY (PROJETO_ID) REFERENCES PROJETO(ID) ON DELETE CASCADE
);

CREATE TABLE ESTR_ENTIDADE (
    ID INT GENERATED ALWAYS AS IDENTITY,
    PROJETO_ID INT NOT NULL,
    NOME VARCHAR(255) NOT NULL,
    DATA_CADASTRO TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT PK_ESTR_ENTIDADE PRIMARY KEY (ID),
    CONSTRAINT FK_ESTR_ENTIDADE_PROJETO FOREIGN KEY (PROJETO_ID) REFERENCES PROJETO(ID) ON DELETE CASCADE
);

CREATE TABLE ESTR_ATRIBUTOS (
    ID_SEQ INT NOT NULL,
    ESTR_ENTIDADE_ID INT NOT NULL,
    NOME_ATRIBUTO VARCHAR(100) NOT NULL,
    TIPO VARCHAR(50) NOT NULL,
    LABEL VARCHAR(255),
    EXIBICAO BOOLEAN NOT NULL DEFAULT TRUE,
    EDITAVEL BOOLEAN NOT NULL DEFAULT TRUE,
    OBRIGATORIO BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT PK_ESTR_ATRIBUTOS PRIMARY KEY (ESTR_ENTIDADE_ID, ID_SEQ),
    CONSTRAINT FK_ESTR_ATRIBUTOS_ESTR_ENTIDADE FOREIGN KEY (ESTR_ENTIDADE_ID) REFERENCES ESTR_ENTIDADE(ID) ON DELETE CASCADE
);

CREATE TABLE ENTIDADE (
    ID_SEQ INT NOT NULL,
    ESTR_ENTIDADE_ID INT NOT NULL,
    DATA_CADASTRO TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT PK_ENTIDADE PRIMARY KEY (ESTR_ENTIDADE_ID, ID_SEQ),
    CONSTRAINT FK_ENTIDADE_ESTR_ENTIDADE FOREIGN KEY (ESTR_ENTIDADE_ID) REFERENCES ESTR_ENTIDADE(ID) ON DELETE CASCADE
);

CREATE TABLE ATRIBUTOS (
    ESTR_ENTIDADE_ID INT NOT NULL,
    ENTIDADE_ID_SEQ INT NOT NULL,
    ESTR_ATRIBUTO_ID_SEQ INT NOT NULL,
    VALOR TEXT,
    CONSTRAINT PK_ATRIBUTOS PRIMARY KEY (ESTR_ENTIDADE_ID, ENTIDADE_ID_SEQ, ESTR_ATRIBUTO_ID_SEQ),
    CONSTRAINT FK_ATRIBUTOS_ENTIDADE FOREIGN KEY (ESTR_ENTIDADE_ID, ENTIDADE_ID_SEQ) REFERENCES ENTIDADE(ESTR_ENTIDADE_ID, ID_SEQ) ON DELETE CASCADE,
    CONSTRAINT FK_ATRIBUTOS_ESTR_ATRIBUTOS FOREIGN KEY (ESTR_ENTIDADE_ID, ESTR_ATRIBUTO_ID_SEQ) REFERENCES ESTR_ATRIBUTOS(ESTR_ENTIDADE_ID, ID_SEQ) ON DELETE CASCADE
);

CREATE TABLE PERGUNTA (
    ID INT GENERATED ALWAYS AS IDENTITY,
    PROJETO_ID INT NOT NULL,
    ESTR_ENTIDADE_ID INT,
    PERGUNTA TEXT NOT NULL,
    TIPO VARCHAR(50) NOT NULL,
    MODELO VARCHAR(50),
    DATA_CADASTRO TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT PK_PERGUNTA PRIMARY KEY (ID),
    CONSTRAINT FK_PERGUNTA_PROJETO FOREIGN KEY (PROJETO_ID) REFERENCES PROJETO(ID) ON DELETE CASCADE,
    CONSTRAINT FK_PERGUNTA_ESTR_ENTIDADE FOREIGN KEY (ESTR_ENTIDADE_ID) REFERENCES ESTR_ENTIDADE(ID) ON DELETE SET NULL
);

CREATE TABLE VALORES_PADRAO (
    PERGUNTA_ID INT NOT NULL,
    VALOR TEXT NOT NULL,
    CONSTRAINT PK_VALORES_PADRAO PRIMARY KEY (PERGUNTA_ID, VALOR),
    CONSTRAINT FK_VALORES_PADRAO_PERGUNTA FOREIGN KEY (PERGUNTA_ID) REFERENCES PERGUNTA(ID) ON DELETE CASCADE
);

CREATE TABLE SUBMISSAO (
    ID INT GENERATED ALWAYS AS IDENTITY,
    PROJETO_ID INT NOT NULL,
    USUARIO_ID INT NOT NULL,
    DATA_CADASTRO TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT PK_SUBMISSAO PRIMARY KEY (ID),
    CONSTRAINT FK_SUBMISSAO_PROJETO FOREIGN KEY (PROJETO_ID) REFERENCES PROJETO(ID) ON DELETE CASCADE,
    CONSTRAINT FK_SUBMISSAO_USUARIO FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO(ID) ON DELETE CASCADE
);

CREATE TABLE RESPOSTA (
    ID INT GENERATED ALWAYS AS IDENTITY,
    SUBMISSAO_ID INT NOT NULL,
    PERGUNTA_ID INT NOT NULL,
    RESPOSTA TEXT,
    ENTIDADE_ESTR_ENTIDADE_ID INT,
    ENTIDADE_ID_SEQ INT,
    CONSTRAINT PK_RESPOSTA PRIMARY KEY (ID),
    CONSTRAINT FK_RESPOSTA_SUBMISSAO FOREIGN KEY (SUBMISSAO_ID) REFERENCES SUBMISSAO(ID) ON DELETE CASCADE,
    CONSTRAINT FK_RESPOSTA_PERGUNTA FOREIGN KEY (PERGUNTA_ID) REFERENCES PERGUNTA(ID) ON DELETE CASCADE,
    CONSTRAINT FK_RESPOSTA_ENTIDADE FOREIGN KEY (ENTIDADE_ESTR_ENTIDADE_ID, ENTIDADE_ID_SEQ) REFERENCES ENTIDADE(ESTR_ENTIDADE_ID, ID_SEQ) ON DELETE SET NULL
);